/* automatically generated by rust-bindgen 0.72.1 */

/** @brief Initialization parameters.
 Optional external allocations are only available for the internal XeSS-FG resources,
 the Swap Chain API resources will still be managed by the API.*/
#[repr(C)]
pub struct _xefg_swapchain_d3d12_init_params_t {
    /// Pointer to the application swap chain.
    pub pApplicationSwapChain: *mut IDXGISwapChain,
    /// Initialization flags.
    pub initFlags: u32,
    /// Maximum number of frames to interpolate, it must be 1.
    pub maxInterpolatedFrames: u32,
    /** Specifies the node mask for internally created resources on
 multi-adapter systems.*/
    pub creationNodeMask: u32,
    /** Specifies the node visibility mask for internally created resources
 on multi-adapter systems.*/
    pub visibleNodeMask: u32,
    /** Optional externally allocated buffer storage for XeSS-FG. If NULL the
 storage is allocated internally. If allocated, the heap type must be
 D3D12_HEAP_TYPE_DEFAULT. This heap is not accessed by the CPU.*/
    pub pTempBufferHeap: *mut ID3D12Heap,
    /// Offset in the externally allocated heap for temporary buffer storage.
    pub bufferHeapOffset: u64,
    /** Optional externally allocated texture storage for XeSS-FG. If NULL the
 storage is allocated internally. If allocated, the heap type must be
 D3D12_HEAP_TYPE_DEFAULT. This heap is not accessed by the CPU.*/
    pub pTempTextureHeap: *mut ID3D12Heap,
    /// Offset in the externally allocated heap for temporary texture storage.
    pub textureHeapOffset: u64,
    /// Pointer to pipeline library. If not NULL, then it will be used for pipeline caching.
    pub pPipelineLibrary: *mut ID3D12PipelineLibrary,
    /** Optional UI handling mode. Use XEFG_SWAPCHAIN_UI_MODE_AUTO to determine UI handling mode internally
 based on provided inputs: hudless color and UI texture.*/
    pub uiMode: xefg_swapchain_ui_mode_t,
}
impl Default for _xefg_swapchain_d3d12_init_params_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/** @brief Initialization parameters.
 Optional external allocations are only available for the internal XeSS-FG resources,
 the Swap Chain API resources will still be managed by the API.*/
pub type xefg_swapchain_d3d12_init_params_t = _xefg_swapchain_d3d12_init_params_t;
/** @brief Contains all fields needed when providing a resource to
 the library, describing its state, lifetime, range and so on.*/
#[repr(C)]
pub struct _xefg_swapchain_d3d12_resource_data_t {
    /// XeSS-FG type of the resource.
    pub type_: xefg_swapchain_resource_type_t,
    /// Time period this resource is valid for.
    pub validity: xefg_swapchain_resource_validity_t,
    /// Base offset to the resource data.
    pub resourceBase: xefg_swapchain_2d_t,
    /// Valid extent of the resource.
    pub resourceSize: xefg_swapchain_2d_t,
    /// D3D12Resource object for this resource.
    pub pResource: *mut ID3D12Resource,
    /// Incoming state of the resource.
    pub incomingState: D3D12_RESOURCE_STATES,
}
impl Default for _xefg_swapchain_d3d12_resource_data_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
/** @brief Contains all fields needed when providing a resource to
 the library, describing its state, lifetime, range and so on.*/
pub type xefg_swapchain_d3d12_resource_data_t = _xefg_swapchain_d3d12_resource_data_t;
pub struct XessLoaded {
    __library: ::libloading::Library,
    pub xefgSwapChainD3D12CreateContext: unsafe extern "C" fn(
        pDevice: *mut ID3D12Device,
        phSwapChain: *mut xefg_swapchain_handle_t,
    ) -> xefg_swapchain_result_t,
    pub xefgSwapChainD3D12BuildPipelines: unsafe extern "C" fn(
        hSwapChain: xefg_swapchain_handle_t,
        pPipelineLibrary: *mut ID3D12PipelineLibrary,
        blocking: bool,
        initFlags: u32,
    ) -> xefg_swapchain_result_t,
    pub xefgSwapChainD3D12InitFromSwapChain: unsafe extern "C" fn(
        hSwapChain: xefg_swapchain_handle_t,
        pCmdQueue: *mut ID3D12CommandQueue,
        pInitParams: *const xefg_swapchain_d3d12_init_params_t,
    ) -> xefg_swapchain_result_t,
    pub xefgSwapChainD3D12InitFromSwapChainDesc: unsafe extern "C" fn(
        hSwapChain: xefg_swapchain_handle_t,
        hWnd: HWND,
        pSwapChainDesc: *const DXGI_SWAP_CHAIN_DESC1,
        pFullscreenDesc: *const DXGI_SWAP_CHAIN_FULLSCREEN_DESC,
        pCmdQueue: *mut ID3D12CommandQueue,
        pDxgiFactory: *mut IDXGIFactory2,
        pInitParams: *const xefg_swapchain_d3d12_init_params_t,
    ) -> xefg_swapchain_result_t,
    pub xefgSwapChainD3D12GetSwapChainPtr: unsafe extern "C" fn(
        hSwapChain: xefg_swapchain_handle_t,
        riid: *const IID,
        ppSwapChain: *mut *mut ::std::os::raw::c_void,
    ) -> xefg_swapchain_result_t,
    pub xefgSwapChainD3D12TagFrameResource: unsafe extern "C" fn(
        hSwapChain: xefg_swapchain_handle_t,
        pCmdList: *mut ID3D12CommandList,
        presentId: u32,
        pResData: *const xefg_swapchain_d3d12_resource_data_t,
    ) -> xefg_swapchain_result_t,
    pub xefgSwapChainD3D12SetDescriptorHeap: unsafe extern "C" fn(
        hSwapChain: xefg_swapchain_handle_t,
        pDescriptorHeap: *mut ID3D12DescriptorHeap,
        descriptorHeapOffsetInBytes: u32,
    ) -> xefg_swapchain_result_t,
}
impl XessLoaded {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let xefgSwapChainD3D12CreateContext = __library
            .get(b"xefgSwapChainD3D12CreateContext\0")
            .map(|sym| *sym)?;
        let xefgSwapChainD3D12BuildPipelines = __library
            .get(b"xefgSwapChainD3D12BuildPipelines\0")
            .map(|sym| *sym)?;
        let xefgSwapChainD3D12InitFromSwapChain = __library
            .get(b"xefgSwapChainD3D12InitFromSwapChain\0")
            .map(|sym| *sym)?;
        let xefgSwapChainD3D12InitFromSwapChainDesc = __library
            .get(b"xefgSwapChainD3D12InitFromSwapChainDesc\0")
            .map(|sym| *sym)?;
        let xefgSwapChainD3D12GetSwapChainPtr = __library
            .get(b"xefgSwapChainD3D12GetSwapChainPtr\0")
            .map(|sym| *sym)?;
        let xefgSwapChainD3D12TagFrameResource = __library
            .get(b"xefgSwapChainD3D12TagFrameResource\0")
            .map(|sym| *sym)?;
        let xefgSwapChainD3D12SetDescriptorHeap = __library
            .get(b"xefgSwapChainD3D12SetDescriptorHeap\0")
            .map(|sym| *sym)?;
        Ok(XessLoaded {
            __library,
            xefgSwapChainD3D12CreateContext,
            xefgSwapChainD3D12BuildPipelines,
            xefgSwapChainD3D12InitFromSwapChain,
            xefgSwapChainD3D12InitFromSwapChainDesc,
            xefgSwapChainD3D12GetSwapChainPtr,
            xefgSwapChainD3D12TagFrameResource,
            xefgSwapChainD3D12SetDescriptorHeap,
        })
    }
    /** @brief Creates a swap chain handle and checks necessary D3D12 features.

 @param pDevice A D3D12 device created by the user.

 @param[out] phSwapChain Pointer to a XeSS-FG swap chain context handle.

 @return XeSS-FG Swap Chain return status code.*/
    pub unsafe fn xefgSwapChainD3D12CreateContext(
        &self,
        pDevice: *mut ID3D12Device,
        phSwapChain: *mut xefg_swapchain_handle_t,
    ) -> xefg_swapchain_result_t {
        (self.xefgSwapChainD3D12CreateContext)(pDevice, phSwapChain)
    }
    /** @brief Initiates pipeline build process
 This function can only be called between @ref xefgSwapChainD3D12CreateContext and
 any initialization function
 This call initiates build of DX12 pipelines and kernel compilation
 This call can be blocking (if @p blocking set to true) or non-blocking.
 In case of non-blocking call library will wait for pipeline build on call to
 initialization function
 If @p pPipelineLibrary passed to this call - same pipeline library must be passed
 to initialization function
 Pipeline build status can be retrieved using @ref xefgSwapChainGetPipelineBuildStatus

 @param hSwapChain The XeSS-FG Swap Chain context handle.
 @param pPipelineLibrary Optional pointer to pipeline library for pipeline caching.
 @param blocking Wait for kernel compilation and pipeline creation to finish or not
 @param initFlags Initialization flags. *Must* be identical to flags passed to initialization function*/
    pub unsafe fn xefgSwapChainD3D12BuildPipelines(
        &self,
        hSwapChain: xefg_swapchain_handle_t,
        pPipelineLibrary: *mut ID3D12PipelineLibrary,
        blocking: bool,
        initFlags: u32,
    ) -> xefg_swapchain_result_t {
        (self
            .xefgSwapChainD3D12BuildPipelines)(
            hSwapChain,
            pPipelineLibrary,
            blocking,
            initFlags,
        )
    }
    /** @brief Initializes the XeSS-FG Swap Chain library for the generation
 and presentation of additional frames.
 The application should call @ref xefgSwapChainD3D12GetSwapChainPtr to retrieve the actual IDXGISwapChain handle.

 @param hSwapChain The XeSS-FG Swap Chain context handle.

 @param pCmdQueue Command queue used by the application
 to present frames. This queue must conform to all restrictions of any IDXGISwapChain.

 @param pInitParams XeSS-FG Swap Chain API initialization parameters.

 @return XeSS-FG Swap Chain return status code.*/
    pub unsafe fn xefgSwapChainD3D12InitFromSwapChain(
        &self,
        hSwapChain: xefg_swapchain_handle_t,
        pCmdQueue: *mut ID3D12CommandQueue,
        pInitParams: *const xefg_swapchain_d3d12_init_params_t,
    ) -> xefg_swapchain_result_t {
        (self.xefgSwapChainD3D12InitFromSwapChain)(hSwapChain, pCmdQueue, pInitParams)
    }
    /** @brief Initializes the XeSS-FG Swap Chain library for the generation
 and presentation of additional frames.
 The application should call @ref xefgSwapChainD3D12GetSwapChainPtr to retrieve the actual IDXGISwapChain handle.

 @param hSwapChain The XeSS-FG Swap Chain context handle.

 @param hWnd Window handle used to create the swap chain.

 @param pSwapChainDesc Swap chain description.

 @param pFullscreenDesc Fullscreen swap chain description. Can be set to NULL.

 @param pCmdQueue Command queue used by the application
 to present frames. This queue must conform to all restrictions of any IDXGISwapChain.

 @param pDxgiFactory IDXGIFactory2 object to be used for the swap chain creation.

 @param pInitParams XeSS-FG Swap Chain API initialization parameters.
 @p pApplicationSwapChain field will not be used and must be set to NULL, a swap chain will be created according to @p hWnd, @p pSwapChainDesc and @p pFullscreenDesc.

 @return XeSS-FG Swap Chain return status code.*/
    pub unsafe fn xefgSwapChainD3D12InitFromSwapChainDesc(
        &self,
        hSwapChain: xefg_swapchain_handle_t,
        hWnd: HWND,
        pSwapChainDesc: *const DXGI_SWAP_CHAIN_DESC1,
        pFullscreenDesc: *const DXGI_SWAP_CHAIN_FULLSCREEN_DESC,
        pCmdQueue: *mut ID3D12CommandQueue,
        pDxgiFactory: *mut IDXGIFactory2,
        pInitParams: *const xefg_swapchain_d3d12_init_params_t,
    ) -> xefg_swapchain_result_t {
        (self
            .xefgSwapChainD3D12InitFromSwapChainDesc)(
            hSwapChain,
            hWnd,
            pSwapChainDesc,
            pFullscreenDesc,
            pCmdQueue,
            pDxgiFactory,
            pInitParams,
        )
    }
    /** @brief Gets a pointer to a DXGI swap chain. The application must use it for
 all presentation in the application.

 @param hSwapChain The XeSS-FG Swap Chain context handle.

 @param riid Type of the interface to which the caller wants a pointer.

 @param[out] ppSwapChain Pointer to a IDXGISwapChain handle.

 @return XeSS-FG Swap Chain return status code.*/
    pub unsafe fn xefgSwapChainD3D12GetSwapChainPtr(
        &self,
        hSwapChain: xefg_swapchain_handle_t,
        riid: *const IID,
        ppSwapChain: *mut *mut ::std::os::raw::c_void,
    ) -> xefg_swapchain_result_t {
        (self.xefgSwapChainD3D12GetSwapChainPtr)(hSwapChain, riid, ppSwapChain)
    }
    /** @brief Informs the XeSS-FG swap chain library of the frame resources used to generate a frame
 that will be presented.

 @attention This function can be used to provide information about the interpolation region within the
 backbuffer by using @p XEFG_SWAPCHAIN_RES_BACKBUFFER resource type. In that case only information about region (size
 and offset) is used from the @p pResData argument.

 @param hSwapChain The swap chain associated with the resource being tagged.

 @param pCmdList Optional command list utilized to manage the resource
 lifetime. It is only required if the resource is not valid until the next
 present call.

 @param presentId The unique frame identifier this resource is associated with.

 @param pResData The resource and the information needed to properly
 manage and interpret it.

 @return XeSS-FG Swap Chain return status code.*/
    pub unsafe fn xefgSwapChainD3D12TagFrameResource(
        &self,
        hSwapChain: xefg_swapchain_handle_t,
        pCmdList: *mut ID3D12CommandList,
        presentId: u32,
        pResData: *const xefg_swapchain_d3d12_resource_data_t,
    ) -> xefg_swapchain_result_t {
        (self
            .xefgSwapChainD3D12TagFrameResource)(
            hSwapChain,
            pCmdList,
            presentId,
            pResData,
        )
    }
    /** @brief Informs the XeSS-FG swap chain library of the descriptor heap to use during frame generation. This API
 needs to be called before presenting a frame. The descriptor heap must be a D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV.

 @param hSwapChain The XeSS-FG Swap Chain context handle.

 @param pDescriptorHeap a pointer to the ID3D12DescriptorHeap object used during interpolation programming.

 @param descriptorHeapOffsetInBytes The offset within @p pDescriptorHeap XeSS-FG will start using during interpolation
 programming, in bytes. This value is number of descriptors to skip times GetDescriptorHandleIncrementSize().

 @return XeSS-FG Swap Chain return status code.*/
    pub unsafe fn xefgSwapChainD3D12SetDescriptorHeap(
        &self,
        hSwapChain: xefg_swapchain_handle_t,
        pDescriptorHeap: *mut ID3D12DescriptorHeap,
        descriptorHeapOffsetInBytes: u32,
    ) -> xefg_swapchain_result_t {
        (self
            .xefgSwapChainD3D12SetDescriptorHeap)(
            hSwapChain,
            pDescriptorHeap,
            descriptorHeapOffsetInBytes,
        )
    }
}
