[workspace]
members = [
  "api_gen",
  "xess-bin",
]

[workspace.package]
authors = ["Traverse Research <support@traverseresearch.nl>"]
edition = "2021"
homepage = "https://traverseresearch.nl"
keywords = ["Intel", "XeSS", "XeLL", "frame generation", "upscaling"]
license = "MIT"
repository = "https://github.com/Traverse-Research/xess-rs"
rust-version = "1.74"
version = "0.1.0+v2.1.0"

[package]
authors.workspace = true
categories = ["external-ffi-bindings", "graphics", "rendering"]
description = "Raw bindings to XeSS"
edition.workspace = true
homepage.workspace = true
include = ["src", "LICENSE"]
keywords.workspace = true
license.workspace = true
name = "xess-sys"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

# Documentation inherited from headers contain indented paragraphs of text
# which are treated as code blocks and hence doc-tested, but obviously fail
# to compile.
[lib]
doctest = false

[dependencies]
ash = { version = "0.38", default-features = false, optional = true }
libloading = { version = "0.8", default-features = false }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", default-features = false, optional = true }

[features]
default = ["vk", "dx12", "xess"]
dx11 = []
dx12 = []
vk = ["dep:ash"]
xell = ["dx12"]
xess = []
xefg_swapchain = ["dx12", "windows/Win32_Graphics_Dxgi_Common", "windows/Win32_Graphics_Direct3D12"]
